version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - "4000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    