openapi: 3.0.0
paths:
  /poker:
    get:
      operationId: PokerController_welcome
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_0
        - poker
  /poker/judge:
    post:
      operationId: PokerController_judge
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PokerHandDto'
      responses:
        '201':
          description: ''
      tags: *ref_0
  /poker/play:
    post:
      operationId: PokerController_play
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayPokerDto'
      responses:
        '201':
          description: ''
      tags: *ref_0
  /health-check:
    get:
      operationId: HealthCheckController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - health-check
info:
  title: Poker
  description: The poker API description
  version: '1.0'
  contact: {}
tags:
  - name: poker
    description: ''
servers: []
components:
  schemas:
    PokerHandDto:
      type: object
      properties: {}
    PlayPokerDto:
      type: object
      properties:
        handList:
          description: 手札のリスト
          type: array
          items:
            type: string
      required:
        - handList
