openapi: 3.0.0
paths:
  /poker:
    get:
      operationId: PokerController_welcome
      parameters: []
      responses:
        '200':
          description: ''
  /poker/judge:
    post:
      operationId: PokerController_judge
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PokerHandDto'
      responses:
        '201':
          description: ''
  /poker/play:
    post:
      operationId: PokerController_play
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayPokerDto'
      responses:
        '201':
          description: ''
info:
  title: Poker
  description: The poker API description
  version: '1.0'
  contact: {}
tags:
  - name: poker
    description: ''
servers: []
components:
  schemas:
    PokerHandDto:
      type: object
      properties: {}
    PlayPokerDto:
      type: object
      properties: {}
