service: poker-api-nestjs

plugins:
  - serverless-layers

custom:
  defaultStage: dev
  profiles:
    dev: kojin-satoki
    prod: prod
  serverless-layers:
    layersDeploymentBucket: poker-api-nestjs-bucket

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  # stage: ${opt.stage, 'dev'}
  profile: kojin-satoki
  # environment:
  #   SERVERLESS_STAGE: ${self:provider.stage}

package:
  individually: true
  include:
    - dist/**
  exclude:
    - "**"

functions:
  index:
    handler: dist/src/lambda.handler
    events:
      - http:
          path: "/"
          method: any
      - http:
          path: "{proxy+}"
          method: any
